/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/v3oJh0gR6dK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Layout() {
  return (
    <>
      <header className="w-full bg-gray-900 py-12 md:py-20 lg:py-24">
        <div className="container mx-auto px-4 md:px-6">
          <div className="mx-auto max-w-3xl text-center">
            <h1 className="text-4xl font-bold tracking-tight text-gray-50 sm:text-5xl lg:text-6xl">John Doe</h1>
            <p className="mt-4 text-lg text-gray-400">
              Game Designer | Passionate about creating immersive experiences
            </p>
            <p className="mt-6 text-gray-400">
              With over a decade of experience in the gaming industry, I have developed a diverse portfolio of
              award-winning titles that have captivated audiences worldwide. My passion for storytelling and innovative
              gameplay mechanics has driven me to push the boundaries of what's possible in the medium.
            </p>
          </div>
        </div>
      </header>
      <section className="w-full py-12 md:py-20 lg:py-24">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="mb-8 text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">Featured Projects</h2>
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            <div className="rounded-lg bg-gray-100 p-6 shadow-md dark:bg-gray-800">
              <img
                alt="Project 1"
                className="mb-4 rounded-lg"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <h3 className="mb-2 text-xl font-bold text-gray-900 dark:text-gray-50">Project 1</h3>
              <p className="text-gray-600 dark:text-gray-400">
                A captivating adventure game that takes players on a thrilling journey through a vast, open world.
              </p>
            </div>
            <div className="rounded-lg bg-gray-100 p-6 shadow-md dark:bg-gray-800">
              <img
                alt="Project 2"
                className="mb-4 rounded-lg"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <h3 className="mb-2 text-xl font-bold text-gray-900 dark:text-gray-50">Project 2</h3>
              <p className="text-gray-600 dark:text-gray-400">
                A fast-paced, action-packed game that challenges players to think strategically and react quickly.
              </p>
            </div>
            <div className="rounded-lg bg-gray-100 p-6 shadow-md dark:bg-gray-800">
              <img
                alt="Project 3"
                className="mb-4 rounded-lg"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <h3 className="mb-2 text-xl font-bold text-gray-900 dark:text-gray-50">Project 3</h3>
              <p className="text-gray-600 dark:text-gray-400">
                A visually stunning puzzle game that combines elements of storytelling and problem-solving.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full bg-gray-100 py-12 md:py-20 lg:py-24 dark:bg-gray-800">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="mb-8 text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">About</h2>
          <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
            <div>
              <h3 className="mb-4 text-2xl font-bold text-gray-900 dark:text-gray-50">Experience and Skills</h3>
              <p className="text-gray-600 dark:text-gray-400">
                With over 10 years of experience in the gaming industry, I have developed a diverse skill set that
                includes game design, level design, user experience, and project management. I am proficient in various
                game engines and programming languages, allowing me to bring my creative visions to life.
              </p>
              <p className="mt-4 text-gray-600 dark:text-gray-400">
                My passion for storytelling and creating immersive experiences has been the driving force behind my
                work. I am constantly seeking new challenges and opportunities to push the boundaries of what's possible
                in the medium of video games.
              </p>
            </div>
            <div>
              <h3 className="mb-4 text-2xl font-bold text-gray-900 dark:text-gray-50">Awards and Recognition</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Over the years, my work has been recognized by industry peers and gaming enthusiasts alike. I have
                received numerous awards and accolades for my contributions to the gaming industry, including:
              </p>
              <ul className="mt-4 list-disc space-y-2 pl-6 text-gray-600 dark:text-gray-400">
                <li>Game of the Year Award (2019)</li>
                <li>Best Narrative Design Award (2021)</li>
                <li>Indie Game of the Year Award (2022)</li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-20 lg:py-24">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="mb-8 text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">Contact</h2>
          <div className="mx-auto max-w-2xl">
            <form className="space-y-6">
              <div>
                <label className="mb-2 block text-sm font-medium text-gray-900 dark:text-gray-50" htmlFor="name">
                  Name
                </label>
                <Input id="name" required type="text" />
              </div>
              <div>
                <label className="mb-2 block text-sm font-medium text-gray-900 dark:text-gray-50" htmlFor="email">
                  Email
                </label>
                <Input id="email" required type="email" />
              </div>
              <div>
                <label className="mb-2 block text-sm font-medium text-gray-900 dark:text-gray-50" htmlFor="message">
                  Message
                </label>
                <Textarea id="message" required rows={5} />
              </div>
              <Button className="w-full" type="submit">
                Submit
              </Button>
            </form>
          </div>
        </div>
      </section>
    </>
  )
}
